export const FAST_CHECK_TASKS = Object.freeze([
  "privacy:check",
  "release-impact:check",
  "release:acceptance:test",
  "release-oauth-canary:test",
  "release-channel:test",
  "release-candidate-manifest:test",
  "promotion-digest:test",
  "prerelease-activation:test",
  "release-soak:test",
  "published-release:test",
  "npm-publication-policy:test",
  "publish-npm:test",
  "runtime-activation:test",
  "candidate-runtime-store:test",
  "release-state:test",
  "release-publication-guard:test",
  "release-ci:test",
  "network-retry:test",
  "release-diagnostic:test",
  "check-runner:test",
  "full-verification-receipt:test",
  "process-output:test",
  "process-nonreplayable:test",
  "github-backlog:test",
  "workflow-policy:test",
  "managed-job-boundary:test",
  "secure-file:test",
  "worker-secret-file:test",
  "device-auth:test",
  "device-root-provider:test",
  "device-key-id-stability:test",
  "dpop:test",
  "security-audit:test",
  "sarif-security:test",
  "sbom-check:test",
  "npm-environment:test",
  "hardened-npm:test",
  "ci-bootstrap:test",
  "consumer-package-security:test",
  "wrangler-toolchain:test",
  "worker-types-generator:test",
  "shell:test",
  "architecture:test",
  "markdown:test",
  "project-metadata:test",
  "numbers:test",
  "records:test",
  "state-inventory:test",
  "state-root-retirement:test",
  "commit-message:test",
  "policy:test",
  "account:test",
  "operation-authorization:test",
  "worker-oauth-controller:test",
  "worker-security:test",
  "policy-docs:check",
  "tool-docs:check",
  "runtime-infrastructure:test",
  "control-plane-resilience:test",
  "runtime-boundaries:test",
  "git-commit:test",
  "runtime-handlers:test",
  "cli-entrypoint:test",
  "cli-service:test",
  "service-restart:test",
  "lifecycle:test",
  "logging-structure:test",
  "worker-runtime-infrastructure:test",
  "relay-http-fallback:test",
  "mcp-protocol:test",
  "mcp-controller:test",
  "mcp-response-proxy:test",
  "mcp:conformance:test",
  "lint:test",
  "lint",
  "typecheck",
  "syntax",
  "deadline:test",
  "catalog:test",
  "tool-arguments:test",
  "capability-ranking:test",
  "execution-routing:test",
  "agent-boundaries:test",
  "browser-identity:test",
  "browser-broker-auth:test",
  "browser-pairing-content:test",
  "browser-pairing-launch:test",
  "browser-cli-pairing:test",
  "resource-admission:test",
  "resource-build-root:test",
  "browser-command:test",
  "browser-devtools-input:test",
  "browser-devtools-observation:test",
  "browser-computer-observation:test",
  "browser-service-worker:test",
  "app-automation:test",
  "browser-request-settlement:test",
  "browser-operation-service:test",
  "app-screenshot:test",
  "macos-background-input:test",
  "computer-use-application-observation:test",
  "computer-use-result-budget:test",
  "computer-use:test",
  "check-plan:test",
]);

export const SERIAL_FAST_CHECK_TASKS = Object.freeze([
  "release:acceptance:test",
  "hardened-npm:test",
  "worker-oauth-controller:test",
  "cli-entrypoint:test",
  "lint",
  "typecheck",
  "syntax",
]);

export const PLATFORM_ONLY_CHECK_TASKS = Object.freeze([
  "privacy:test",
  "release-impact:test",
  "worker-deployment:test",
  "relay:test",
  "security-properties:test",
  "process-lock:test",
  "service-lifecycle:test",
  "service-environment:test",
  "service-platform:test",
  "delegated-sandbox:test",
  "macos-trust:test",
  "macos-native-build:test",
  "agent-context:test",
  "browser-page-automation:test",
  "self-test",
  "atomic-fs:test",
  "ssh-key:test",
  "full-access:test",
  "managed-jobs:test",
]);

export const FULL_PREFLIGHT_CHECK_TASKS = Object.freeze([
  "sbom:test",
]);

export const FULL_POST_PLATFORM_CHECK_TASKS = Object.freeze([
  "coverage:test",
  "browser-bridge:test",
  "package:test",
  "install:test",
  "stdio:integration-test",
  "worker:integration-test",
  "oauth-browser:test",
]);

export const FULL_ONLY_CHECK_TASKS = Object.freeze([
  ...FULL_PREFLIGHT_CHECK_TASKS,
  ...FULL_POST_PLATFORM_CHECK_TASKS,
]);

export const PLATFORM_CHECK_TASKS = Object.freeze([
  ...FAST_CHECK_TASKS,
  ...PLATFORM_ONLY_CHECK_TASKS,
]);

export const FULL_CHECK_TASKS = Object.freeze([
  ...FULL_PREFLIGHT_CHECK_TASKS,
  ...FAST_CHECK_TASKS,
  ...PLATFORM_ONLY_CHECK_TASKS,
  ...FULL_POST_PLATFORM_CHECK_TASKS,
]);

export function checkTasks(mode) {
  if (mode === "fast") return FAST_CHECK_TASKS;
  if (mode === "platform") return PLATFORM_CHECK_TASKS;
  if (mode === "full") return FULL_CHECK_TASKS;
  throw new Error(`unknown check mode: ${mode}`);
}
